DELIMITER //

CREATE FUNCTION calcular_impuesto(
    salario DECIMAL(10,2)
)
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
	RETURN salario * 0.10;
END //
DELIMITER ;

SELECT NOMBRE, calcular_impuesto(250) AS IMPUESTOS FROM EMPLEADOS;